package com.example.fcms.service;

import com.example.fcms.entity.*;
import com.example.fcms.repository.*;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
@Transactional
public class TeacherQuestionService {

    private final QuestionRepository questionRepository;
    private final QuestionOptionRepository questionOptionRepository;
    private final LearningNodeRepository learningNodeRepository;

    public TeacherQuestionService(QuestionRepository questionRepository,
                                  QuestionOptionRepository questionOptionRepository,
                                  LearningNodeRepository learningNodeRepository) {
        this.questionRepository = questionRepository;
        this.questionOptionRepository = questionOptionRepository;
        this.learningNodeRepository = learningNodeRepository;
    }

    public List<Question> getTeacherQuestions(Long teacherId) {
        return questionRepository.findByTeacher_UserIdOrderByCreatedAtDesc(teacherId);
    }

    public List<Question> getQuestionsWithOptions(Long teacherId) {
        List<Question> questions = questionRepository.findByTeacher_UserIdOrderByCreatedAtDesc(teacherId);
        // Hibernate initialization happens if lazy load, but this ensures safe mapping if needed
        return questions;
    }

    public List<QuestionOption> getOptions(Long questionId) {
        return questionOptionRepository.findByQuestion_QuestionId(questionId);
    }

    public Question createQuestion(User teacher, String content, String type, String difficulty, 
                                   String answer, String explanation, Long nodeId,
                                   List<String> options, Integer correctOptionIndex) {
        LearningNode node = null;
        if (nodeId != null) {
            node = learningNodeRepository.findById(nodeId).orElse(null);
        }

        Question question = Question.builder()
                .teacher(teacher)
                .learningNode(node)
                .questionContent(content)
                .questionType(type)
                .difficulty(difficulty)
                .correctAnswer(answer)
                .explanation(explanation)
                .sourceType("MANUAL")
                .status("APPROVED")
                .build();

        question = questionRepository.save(question);

        if ("MCQ".equalsIgnoreCase(type) && options != null) {
            for (int i = 0; i < options.size(); i++) {
                String optionText = options.get(i);
                if (optionText == null || optionText.trim().isEmpty()) continue;
                
                boolean isCorrect = (correctOptionIndex != null && correctOptionIndex == i);
                QuestionOption opt = QuestionOption.builder()
                        .question(question)
                        .optionText(optionText)
                        .isCorrect(isCorrect)
                        .build();
                questionOptionRepository.save(opt);
                
                if (isCorrect) {
                    // Update main correctAnswer label (e.g. A, B, C, D)
                    char choice = (char) ('A' + i);
                    question.setCorrectAnswer(String.valueOf(choice));
                    questionRepository.save(question);
                }
            }
        }

        return question;
    }

    public void deleteQuestion(Long teacherId, Long questionId) {
        Question question = questionRepository.findById(questionId).orElse(null);
        if (question != null && question.getTeacher().getUserId().equals(teacherId)) {
            questionOptionRepository.deleteByQuestion_QuestionId(questionId);
            questionRepository.delete(question);
        }
    }

    public void generateAiQuestions(User teacher, Long nodeId, String topicName) {
        LearningNode node = null;
        if (nodeId != null) {
            node = learningNodeRepository.findById(nodeId).orElse(null);
        }

        String finalTopic = (node != null) ? node.getTitle() : (topicName != null ? topicName : "General Concepts");

        // Generate 3 Mocked AI Questions
        for (int i = 0; i < 3; i++) {
            String content = "";
            String difficulty = i == 0 ? "EASY" : (i == 1 ? "MEDIUM" : "HARD");
            String explanation = "Automatically generated by AI based on course curriculum objectives.";
            
            List<String> optionsList = new ArrayList<>();
            int correctIdx = 0;
            String answer = "A";

            if (i % 3 == 0) {
                content = "Which of the following describes the key principle behind " + finalTopic + "?";
                optionsList.add("To facilitate active self-study prior to class sessions.");
                optionsList.add("To delay reading slides and doing assignments until the exam period.");
                optionsList.add("To rely purely on memorize-only style learning methods.");
                optionsList.add("To completely ignore pre-class preparation tasks.");
                explanation = "Flipped learning emphasizes pre-class self-study and active classroom discussions.";
            } else if (i % 3 == 1) {
                content = "What is a main benefit of applying " + finalTopic + " in software engineering courses?";
                optionsList.add("It enhances student collaboration and problem-solving skills.");
                optionsList.add("It decreases class attendance rate and decreases overall performance.");
                optionsList.add("It makes the course syllabus optional and ignores exams.");
                optionsList.add("It requires no teacher involvement or grading guidelines.");
                explanation = "Active student collaboration improves critical thinking and real-world application.";
            } else {
                content = "To successfully master " + finalTopic + ", students should prioritize:";
                optionsList.add("Doing hands-on exercises and reviewing feedback regularly.");
                optionsList.add("Copying test answers directly from external forums.");
                optionsList.add("Only reading slide titles and ignoring material details.");
                optionsList.add("Skipping all AI practice questions and self-study sessions.");
                explanation = "Hands-on exercises and regular review form the foundation of flipped mastery.";
            }

            Question question = Question.builder()
                    .teacher(teacher)
                    .learningNode(node)
                    .questionContent(content)
                    .questionType("MCQ")
                    .difficulty(difficulty)
                    .correctAnswer(answer)
                    .explanation(explanation)
                    .sourceType("AI_GENERATED")
                    .status("APPROVED")
                    .build();

            question = questionRepository.save(question);

            for (int o = 0; o < optionsList.size(); o++) {
                QuestionOption opt = QuestionOption.builder()
                        .question(question)
                        .optionText(optionsList.get(o))
                        .isCorrect(o == correctIdx)
                        .build();
                questionOptionRepository.save(opt);
            }
        }
    }
}
